In [48]:
import numpy as np;

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])



In [49]:

a_negs=a[a<0]
print(f'There are: {len(a_negs)}  negative numbers in a which are: {a_negs}')



There are: 4  negative numbers in a which are: [-2 -1 -6 -7]


In [50]:

a_pos=a[a>0]
print(f'There are: {len(a_pos)}  positive numbers in a which are: {a_pos}')


There are: 5  positive numbers in a which are: [ 4 10 12 23  3]


In [51]:


# a_pos_even=a_pos[a_pos%2==0]
# print(f'There are: {len(a_pos_even)}  positive numbers in a which are: {a_pos_even}')
#how do we chain booleans?
#like so
a_pos_even=a[(a%2==0)&(a>0)]
print(f'There are: {len(a_pos_even)}  positive numbers in a which are: {a_pos_even}')


There are: 3  positive numbers in a which are: [ 4 10 12]


In [52]:



a_plus_3=a+3
a_plus_3_pos=a_plus_3[a_plus_3>0]
print(f'There are: {len(a_plus_3_pos)}  positive numbers in a which are: {a_plus_3_pos}')


There are: 10  positive numbers in a which are: [ 7 13 15 26  1  2  3  3  3  6]


In [53]:

a_squared=a**2
print(f'{a_squared} mean: {a_squared.mean():.2f}  std: {np.std(a_squared):.2f}')


[ 16 100 144 529   4   1   0   0   0  36   9  49] mean: 74.00  std: 144.02


In [54]:

a_centered=a-a.mean()
print(f'a centered: {a_centered}')


a centered: [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [55]:

a_zscore=(a-a.mean())/np.std(a)
a_zscore=a_zscore.round(2)
print(f'z-score for a is: {a_zscore}')




z-score for a is: [ 0.12  0.87  1.12  2.48 -0.62 -0.5  -0.37 -0.37 -0.37 -1.12  0.   -1.24]


In [56]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a=sum(a)
print(f'This is sum_of_a: {sum_of_a}')


This is sum_of_a: 55


In [57]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a=min(a)
print(f'This is min_of_a: {min_of_a}')


This is min_of_a: 1


In [58]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a=max(a)
print(f'This is max_of_a: {max_of_a}')


This is max_of_a: 10


In [59]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a=sum_of_a/len(a)
print(f'This is mean_of_a: {mean_of_a}')


This is mean_of_a: 5.5


In [60]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a= 1
for i in a:
    product_of_a*=i
print(f'This is product_of_a: {product_of_a:,.2f}')


This is product_of_a: 3,628,800.00


In [61]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a=[]
for i in a:
    squares_of_a=i**2
print(f'This is squares_of_a: {squares_of_a}')


This is squares_of_a: 100


In [62]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a=[]
for i in a:
    if i %2 !=0:
        odds_in_a.append(i)
print(f'This is odds_in_a: {odds_in_a}')


This is odds_in_a: [1, 3, 5, 7, 9]


In [63]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a=[]
for i in a:
    if i %2 ==0:
        odds_in_a.append(i)
print(f'This is evens_in_a: {evens_in_a}')


This is evens_in_a: []


In [64]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard
# print(f'This is A: {A}')
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b=np.array(b)



In [65]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
  
print(sum_of_b)
sum_of_b=b.sum()
print(sum_of_b)


33
33


In [66]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
print(min_of_b)
min_of_b=b.min()
print(min_of_b)


3
3


In [67]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)
max_of_b=b.max()
print(max_of_b)



8
8


In [68]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)
mean_of_b=b.mean()
print(mean_of_b)


5.5
5.5


In [69]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(min_of_b)
product_of_b=b.prod()
print(min_of_b)


3
3


In [70]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)
squares_of_b=b**2
print(squares_of_b)



[9, 16, 25, 36, 49, 64]
[[ 9 16 25]
 [36 49 64]]


In [71]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

print(odds_in_b)
odds_in_b=b[b%2!=0]
print(odds_in_b)


[3, 5, 7]
[3 5 7]


In [72]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

print(evens_in_b)
evens_in_b=b[b%2==0]
print(evens_in_b)


[4, 6, 8]
[4 6 8]


In [73]:
# Exercise 9 - print out the shape of the array b.
shape_of_b=b.shape
print('Shape',(shape_of_b))


Shape (2, 3)


In [74]:
# Exercise 10 - transpose the array b.
tpose_of_b=b.T
print(tpose_of_b)


[[3 6]
 [4 7]
 [5 8]]


In [75]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
reshape_b_1by6=b.reshape(1,6)
print('reshape_b_1by6',reshape_b_1by6)


reshape_b_1by6 [[3 4 5 6 7 8]]


In [76]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
reshape_b_6by1=reshape_b_1by6.T
print('reshape_b_6by1',reshape_b_6by1)


reshape_b_6by1 [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [77]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c=np.array(c)
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print('Find the min, max, sum, and product of c',c.min(),c.max(),c.sum(),c.prod())



Find the min, max, sum, and product of c 1 9 45 362880


In [78]:
# Exercise 2 - Determine the standard deviation of c.
std_c=np.std(c)
print('std_c',std_c)


std_c 2.581988897471611


In [79]:
# Exercise 3 - Determine the variance of c.
var_c=std_c**2
print('var_c',var_c)


var_c 6.666666666666666


In [80]:
# Exercise 4 - Print out the shape of the array c
print('c.shape',c.shape)



c.shape (3, 3)


In [81]:
# Exercise 5 - Transpose c and print out transposed result.
tpose_c=c.T
print('c.T',tpose_c)



c.T [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [82]:
# Exercise 6 - Get the dot product of the array c with c. 
c_dot_c=np.dot(c,c)
print('c_dot_c',c_dot_c)


c_dot_c [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [83]:

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
sum_c_by_cT=(c*c.T).sum()
print('sum c dot cT',sum_c_by_cT)


sum c dot cT 261


In [84]:

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
ex_8=c*c.T
ex_8=np.prod(ex_8)
print('ex8',ex_8)
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d=np.array(d)


ex8 131681894400


In [85]:

# Exercise 1 - Find the sine of all the numbers in d
sine_d=(np.sin(d)).round(3)
print('sin d',sine_d)


sin d [[ 0.894 -0.988  0.851  0.     0.581 -0.801]
 [ 0.851 -0.894  0.988 -0.176  0.894  0.   ]
 [-0.305  0.851 -0.851  0.894 -0.851 -0.801]]


In [86]:

# Exercise 2 - Find the cosine of all the numbers in d
cos_d=(np.cos(d)).round(3)
print('sin d',cos_d)


sin d [[-0.448  0.154  0.525  1.     0.814 -0.598]
 [ 0.525 -0.448  0.154  0.984 -0.448  1.   ]
 [-0.952  0.525  0.525 -0.448  0.525 -0.598]]


In [87]:

# Exercise 3 - Find the tangent of all the numbers in d
tan_d=(np.tan(d)).round(3)
print('sin d',tan_d)


sin d [[-1.995 -6.405  1.62   0.     0.713  1.339]
 [ 1.62   1.995  6.405 -0.179 -1.995  0.   ]
 [ 0.32   1.62  -1.62  -1.995 -1.62   1.339]]


In [88]:

# Exercise 4 - Find all the negative numbers in d
neg_d=d[d<0]
print('neg_d',neg_d)


neg_d [-90 -30 -45 -45]


In [89]:

# Exercise 5 - Find all the positive numbers in d
pos_d=d[d>0]
print('pos d',pos_d)


pos d [ 90  30  45 120 180  45 270  90  60  45  90 180]


In [90]:

# Exercise 6 - Return an array of only the unique numbers in d.
unique_d=np.unique(d)
print('unique',unique_d)


unique [-90 -45 -30   0  30  45  60  90 120 180 270]


In [91]:

# Exercise 7 - Determine how many unique numbers there are in d.
count_unique_d=unique_d.size
print('count unique',count_unique_d)


count unique 11


In [92]:

# Exercise 8 - Print out the shape of d.
shape_d=d.shape
print('shape_d',shape_d)


shape_d (3, 6)


In [93]:

# Exercise 9 - Transpose and then print out the shape of d.
shape_dT=d.T.shape
print('shape_dT',shape_dT)


shape_dT (6, 3)


In [94]:

# Exercise 10 - Reshape d into an array of 9 x 2
reshapeD=d.reshape(9,2)
print('reshapeD',reshapeD.shape)







reshapeD (9, 2)
